name            = 'cat'
author          = 'Labricecat'
description     = ''
cpp             = 20
github          = 'labricecat/cat'
license         = [ 'MIT', 'https://github.com/labricecat/cat/blob/main/LICENSE' ]
show_includes   = true
changelog       = false
navbar          = [ 'namespaces', 'classes', 'files', 'github' ]
theme           = 'dark'
robots = true
stylesheets = [
    'https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400i,600,600i%7CSource+Code+Pro:400,400i,600'
]

[warnings]
enabled         = true
treat_as_errors = false
undocumented    = true

[sources]
paths           = [ 'inc', '.' ]
recursive_paths = [ 'inc' ]
patterns        = [ '*.hpp', '*.md' ]
strip_paths     = [ 'inc', 'src' ]
extract_all = true

[examples]
paths           = 'examples'
recursive_paths = [ 'inc' ]
patterns        = [ '*.hpp' ]

